<?php

namespace App\Http\Requests\API;

use Illuminate\Foundation\Http\FormRequest;

class DemandRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "provider_id" => "required|exists:providers,id",
            "user_id" => "required|exists:users,id",
            "name" => "required",
            "phone" => "required",
            "note"  => ""
        ];
    }

    protected function getValidatorInstance()
    {
        $this->request->add(["user_id" => auth()->id()]);
        $this->query->add(["user_id" => auth()->id()]);

        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
