<?php

namespace App\Http\Requests\API;

use Auth;
use Illuminate\Foundation\Http\FormRequest;

class IssueRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'category_id' => "required",
            'user_id' => 'required',
            "area_id" => "required",
            "title" => "required",
            "description" => "required",
            "from" => "required|date",
            "to" => "required|date|after:from",
            'type' => 'required',
            'images' => 'array',
            'images.*' => 'image'
        ];
    }

    protected function getValidatorInstance()
    {
        $this->request->add(['user_id' => Auth::id()]);
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
