<?php

namespace App\Http\Requests\API;

use Illuminate\Foundation\Http\FormRequest;

class PaymentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "user_id" => "required",
            "request_id" => "required"
        ];
    }

    protected function getValidatorInstance()
    {
        $this->request->add(["user_id" => auth()->id()]);
        $this->query->add(["user_id" => auth()->id()]);
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
