<?php

namespace App\Http\Requests\Admin;

use Auth;
use Illuminate\Foundation\Http\FormRequest;

class UserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email|unique:users,email',
            'phone' => 'required',
            'gender' => 'required',
            'type' => 'required',
            'area_id' => 'required',
        ];

        if ($this->isMethod('POST')) {
            $rules['password'] = 'required';
        }

        if ($this->isMethod('PUT') || $this->isMethod('PATCH')) {
            $rules['email'] = 'required|email';
        }

        return $rules;
    }

    protected function getValidatorInstance()
    {
        if (
            !Auth::user()->hasAccess("admin.users.edit.password")
            and ($this->isMethod('PUT') || $this->isMethod('PATCH'))
        ) {
            $this->request->remove("password");
            $this->query->remove("password");
        }
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
